### ISSUE TITLE
Suggestion: single file with "hello cube"

### ISSUE THREAD

**Issue by artBoffin** [xem/MiniShadertoy#3]
Suggestion:

Create a single file with a "hello cube" as an example of how to use the tiny library (comments could be helpful)

Basically, porting this over:
https://xem.github.io/webgl-guide/editor/?demo=8

**Comment by xem** [comment]
Hello!
Unfortunately, Shadertoy (and my mini Shadertoy clone) don't allow trace polygons. It's only a flat surface where devs and artists compute and apply an interactive texture with various techniques, but none of them involve triangles, so it's not possible to use the Hello Cube demo in here.
However, I explain how to make cubes on shadertoy here: https://xem.github.io/articles/webgl_quest_2.html
Cheers!
Max
